version: "3.9"

services:
    app:
        build: .
        container_name: tg_bot_vpn
        restart: always
        ports:
            - "0.0.0.0:4004:${APP_PORT:-4004}"
        env_file:
            - .env
        volumes:
            - sqlite-data:/app/data
        command: ["./server"]
volumes:
    sqlite-data:
